Optimize document time expression
open-telemetry/community pull request #2103
Opened 2024-05-10 15:35 UTC by steverao

Optimize document time expression

2024-05-12 00:25 UTC, trask approved these changes

2024-05-13 06:30 UTC, svrnm requested changes
This section is auto-generated from https://github.com/open-telemetry/community/blob/main/sigs.yml, can you update that file and run `make table-generation` to update the README from there

2024-05-13 08:46 UTC, steverao commented
> This section is auto-generated from https://github.com/open-telemetry/community/blob/main/sigs.yml, can you update that file and run `make table-generation` to update the README from there

done

2024-05-13 09:24 UTC, svrnm approved these changes

2024-05-13 09:24 UTC, merged